2021-11-17 21:14:40,513 - bot - INFO - START bot
2021-11-17 21:14:40,514 - apscheduler.scheduler - INFO - Scheduler started
2021-11-17 21:15:28,985 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/elenaefimova/Documents/Github/pybot/venv/lib/python3.9/site-packages/telegram/ext/dispatcher.py", line 555, in process_update
    handler.handle_update(update, self, check, context)
  File "/Users/elenaefimova/Documents/Github/pybot/venv/lib/python3.9/site-packages/telegram/ext/handler.py", line 198, in handle_update
    return self.callback(update, context)
  File "/Users/elenaefimova/Documents/Github/pybot/main.py", line 36, in bot_help
    context.bot.sendMessage(help_string, context.bot, update)
  File "/Users/elenaefimova/Documents/Github/pybot/venv/lib/python3.9/site-packages/telegram/bot.py", line 130, in decorator
    result = func(*args, **kwargs)
  File "/Users/elenaefimova/Documents/Github/pybot/venv/lib/python3.9/site-packages/telegram/bot.py", line 513, in send_message
    return self._message(  # type: ignore[return-value]
  File "/Users/elenaefimova/Documents/Github/pybot/venv/lib/python3.9/site-packages/telegram/ext/extbot.py", line 199, in _message
    result = super()._message(
  File "/Users/elenaefimova/Documents/Github/pybot/venv/lib/python3.9/site-packages/telegram/bot.py", line 332, in _message
    result = self._post(endpoint, data, timeout=timeout, api_kwargs=api_kwargs)
  File "/Users/elenaefimova/Documents/Github/pybot/venv/lib/python3.9/site-packages/telegram/bot.py", line 295, in _post
    return self.request.post(
  File "/Users/elenaefimova/Documents/Github/pybot/venv/lib/python3.9/site-packages/telegram/utils/request.py", line 364, in post
    body=json.dumps(data).encode('utf-8'),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ExtBot is not JSON serializable
2021-11-17 21:16:15,751 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2021-11-17 21:16:15,753 - apscheduler.scheduler - INFO - Scheduler has been shut down
2021-11-17 21:19:31,445 - bot - INFO - START bot
2021-11-17 21:19:31,446 - apscheduler.scheduler - INFO - Scheduler started
2021-11-17 21:20:29,483 - telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
2021-11-17 21:20:29,483 - apscheduler.scheduler - INFO - Scheduler has been shut down
